name: Update Playlist and EPG

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Generate updated playlist
        run: python generate_playlist.py

      - name: Sanitize playlist
        run: python sanitize_playlist.py

      - name: Clone EPG repo
        run: git clone https://github.com/iptv-org/epg.git

      - name: Install EPG dependencies
        run: |
          cd epg
          npm install

      - name: Generate guide.xml
        run: |
          cd epg
          npx tsx scripts/commands/epg/grab.ts --channels=../verified_curated_full.m3u --output=../guide.xml

      - name: Commit and push updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update playlist and guide"
          file_pattern: "verified_curated_full.m3u guide.xml invalid_tvg_ids.log"
